version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: springboot-app-2
    restart: always
    build: .
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - C:\Users\lucam\OneDrive\Desktop\db:\var\lib\mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_estimate_2
      MYSQL_ROOT_PASSWORD: root